#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// Paths
const SRC_DIR = path.join(__dirname, 'src');
const ICONS_DIR = path.join(SRC_DIR, 'icons');
const OUTPUT_FILE = path.join(SRC_DIR, 'modules', 'embeddedAssets.js');
const BUILD_INFO_FILE = path.join(SRC_DIR, 'modules', 'buildInfo.js');

// Read version from package.json
const packageJson = JSON.parse(fs.readFileSync(path.join(__dirname, 'package.json'), 'utf8'));
const version = packageJson.version;

// Convert version to short format: "1.1.0" -> "0101" (major + minor, zero-padded)
function getVersionSuffix(version) {
    const parts = version.split('.');
    const major = parseInt(parts[0] || 0, 10);
    const minor = parseInt(parts[1] || 0, 10);
    return String(major).padStart(2, '0') + String(minor).padStart(2, '0');
}

const versionSuffix = getVersionSuffix(version);

console.log('🎨 Building embedded assets...\n');
console.log(`📌 Version: ${version} (suffix: v${versionSuffix})\n`);

// Find all PNG files in icons directory
const iconFiles = fs.readdirSync(ICONS_DIR)
    .filter(f => f.endsWith('.png'))
    .sort();

console.log(`📦 Found ${iconFiles.length} PNG icons:\n`);

// Process each icon
const assets = {};
for (const filename of iconFiles) {
    const filePath = path.join(ICONS_DIR, filename);
    const buffer = fs.readFileSync(filePath);
    const base64 = buffer.toString('base64');
    const sizeKB = (buffer.length / 1024).toFixed(1);
    
    // Get base name without extension: "icon-apply.png" -> "icon-apply"
    const baseName = path.basename(filename, '.png');
    
    // Create versioned filename: "icon-apply_v0101.png"
    const versionedName = `${baseName}_v${versionSuffix}.png`;
    
    assets[baseName] = {
        versionedName: versionedName,
        base64: base64
    };
    
    console.log(`  ✓ ${filename} -> ${versionedName} (${sizeKB} KB)`);
}

// Generate the module code
const moduleCode = `// ============================================================================
// EMBEDDED ASSETS - Auto-generated by build.js
// Do not edit this file directly. Run: npm run build:assets
// ============================================================================

// Asset version suffix (from package.json version ${version})
export var ASSETS_VERSION = "${versionSuffix}";

// Runtime path - set by initializeAssets()
var assetsPath = null;

// Embedded base64 data
var EMBEDDED_ASSETS = {
${Object.entries(assets).map(([baseName, data]) => 
    `    "${data.versionedName}": "${data.base64}"`
).join(',\n')}
};

/**
 * Initialize the embedded assets system.
 * Creates temp folder and writes icons if they don't exist.
 * Must be called before using getAssetPath().
 */
export function initializeAssets() {
    assetsPath = api.getTempFolder() + "/easey_assets_v" + ASSETS_VERSION + "/";
    
    // Create folder if it doesn't exist
    if (!api.isDirectory(assetsPath)) {
        api.makeFolder(assetsPath);
    }
    
    // Write each asset if it doesn't exist
    for (var filename in EMBEDDED_ASSETS) {
        var filePath = assetsPath + filename;
        if (!api.isFile(filePath)) {
            var base64Data = EMBEDDED_ASSETS[filename];
            api.writeEncodedToBinaryFile(filePath, base64Data);
        }
    }
    
    return assetsPath;
}

/**
 * Get the full path to an asset.
 * @param {string} name - Base name without extension (e.g., "icon-apply")
 * @returns {string} Full path to the versioned asset file
 */
export function getAssetPath(name) {
    if (!assetsPath) {
        throw new Error("Assets not initialized. Call initializeAssets() first.");
    }
    return assetsPath + name + "_v" + ASSETS_VERSION + ".png";
}
`;

// Write the module
fs.writeFileSync(OUTPUT_FILE, moduleCode, 'utf8');

console.log(`\n✅ Generated ${path.relative(__dirname, OUTPUT_FILE)}`);
console.log(`   Assets folder: easey_assets_v${versionSuffix}/`);
console.log(`   Total assets: ${Object.keys(assets).length}`);

// Build ID - fresh every build, shown next to the version in the settings menu
// so a running script can be matched to the build it came from. Deliberately
// not committed; it is regenerated before every bundle.
const buildId = crypto.randomBytes(3).toString('hex');

fs.writeFileSync(BUILD_INFO_FILE, `// ============================================================================
// BUILD INFO - Auto-generated by build.cjs
// Do not edit or commit this file. Regenerated on every build.
// ============================================================================

export var BUILD_ID = "${buildId}";
`, 'utf8');

console.log(`\n🔖 Build ID: ${buildId}`);
