// ============================================================================
// EMBEDDED ASSETS - Auto-generated by build.js
// Do not edit this file directly. Run: npm run build:assets
// ============================================================================

// Asset version suffix (from package.json version 2.0.0)
export var ASSETS_VERSION = "0200";

// Runtime path - set by initializeAssets()
var assetsPath = null;

// Embedded base64 data
var EMBEDDED_ASSETS = {
    "icon-settings_v0200.png": "iVBORw0KGgoAAAANSUhEUgAAAEQAAABECAYAAAA4E5OyAAAACXBIWXMAACxLAAAsSwGlPZapAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAOUSURBVHgB7ZvtbdswEIbPRf7X2UDZwN3AmaDNBFY2SCfoCO0GTidIO4G9QbMBtYHdCd6SEd2ysqQjxSMtGXoAwoBEitQrfhyPZ6KZmZmZiQBgrdMB/iidVnSt6Jf7hXAUZeQd5WVJIye3IKMnWhDdpZdmnOtU0IWwbVjTpTEi2InvxIbJrxCOYp65wb+JWl3sw7SIwYoCYUGsGGf5s4vSI0avKBAUpEOM/KJ4iNEpCsJskE5BGDHyiRIgxomNU3aF4awDxTihECjKwjejffBOp4LCeNbpqFNJw+0QU/6HLf+Jwqh0ul8sFpVPZi9BIsQYCxV5iuIriBnHBU2bSqcPWpRjXybWMLPjt6DpU5DHe/hYqq9Uj+FrgH0PVhDbxT7T9Hn0nVi90EOnhBw7nZ5QL8VLp463PYm9t4McJaUA8aJsEWAXoLZ7nhFHSSkZKIpChOcL4QZhHjGcBoaIYr5wtGMI9XB6Cai3pJx4Nu6FhIHfENrSQGIcRNwSVun0SPI82Wf38ZtyAj/veUGJAL9RNG0bNGct2irTP1xXL5j7z3rNT9E7/mKGjv7ZMNmO1N2T3+wr3c69e7FNEIl9y52oEdSC7YGxRxRH3c5b90LbHFJQHPvUYhhsHXuK42z1S3EM8ZPyIV5XCkFeKR97EqZtDgHFccv5HKRAbfAdKALd1v80EBekWUFqpNs7H2U2EBcEAvuWS9aVoocUlA/x2JEUgqwpH5MQ5CPlQ7yutlXGLGOxY3Mqpnul23nnXrhpyfSg01fqFmVJvGBfKM3Wv1kHR8XcfyAJ7Pab2/4nC5ZD7VLktv9ryomu8BvTKJViWUTtSlRM3RfxmL1n7hdUDz1ptsQv7XmD+xAWkvACOSfzNqDeDeUgUIwTChEuRdRzlkI4aUUZKIbLFuEHVVvEkUYUxIvhskN9XGmc1c2jzBXkjzJlRYGsGJfCSxTWdwEZi3AMGKfVXXTADE0gPt0T8x6ssegjSEW8CTwFquYZTBu+ATP3NG1RKqrfgSVHWKYJpzRnrWarHhOW+d2WD10xKgoIywwC4XEapVN2jeGsnOeUAeUURhTNXLaU9SnX5NDyHB9RVHIxyF+UsqOcQjhdwf/lKMRwGtQlStlTRiGcvr+HlKMQw2mQK8oBTBgT0vyBqByFGC5o7El68imEw1rJ9sOsIOBmuCEBfAyelEguqfNRZoMpCHItcfbnINzzld97PjMzMxPBH4BGhiHoIQdCAAAAAElFTkSuQmCC"
};

/**
 * Initialize the embedded assets system.
 * Creates temp folder and writes icons if they don't exist.
 * Must be called before using getAssetPath().
 */
export function initializeAssets() {
    assetsPath = api.getTempFolder() + "/easey_assets_v" + ASSETS_VERSION + "/";
    
    // Create folder if it doesn't exist
    if (!api.isDirectory(assetsPath)) {
        api.makeFolder(assetsPath);
    }
    
    // Write each asset if it doesn't exist
    for (var filename in EMBEDDED_ASSETS) {
        var filePath = assetsPath + filename;
        if (!api.isFile(filePath)) {
            var base64Data = EMBEDDED_ASSETS[filename];
            api.writeEncodedToBinaryFile(filePath, base64Data);
        }
    }
    
    return assetsPath;
}

/**
 * Get the full path to an asset.
 * @param {string} name - Base name without extension (e.g., "icon-apply")
 * @returns {string} Full path to the versioned asset file
 */
export function getAssetPath(name) {
    if (!assetsPath) {
        throw new Error("Assets not initialized. Call initializeAssets() first.");
    }
    return assetsPath + name + "_v" + ASSETS_VERSION + ".png";
}
